/** Official U.S. state names (Census / USPS). There is no separate Spanish legal spelling. */
function st(slug, name) {
  return { slug, nameEs: name, nameEn: name };
}

module.exports = {
  AL: st("alabama", "Alabama"),
  AK: st("alaska", "Alaska"),
  AZ: st("arizona", "Arizona"),
  AR: st("arkansas", "Arkansas"),
  CA: st("california", "California"),
  CO: st("colorado", "Colorado"),
  CT: st("connecticut", "Connecticut"),
  DE: st("delaware", "Delaware"),
  DC: st("district-of-columbia", "District of Columbia"),
  FL: st("florida", "Florida"),
  GA: st("georgia", "Georgia"),
  HI: st("hawaii", "Hawaii"),
  ID: st("idaho", "Idaho"),
  IL: st("illinois", "Illinois"),
  IN: st("indiana", "Indiana"),
  IA: st("iowa", "Iowa"),
  KS: st("kansas", "Kansas"),
  KY: st("kentucky", "Kentucky"),
  LA: st("louisiana", "Louisiana"),
  ME: st("maine", "Maine"),
  MD: st("maryland", "Maryland"),
  MA: st("massachusetts", "Massachusetts"),
  MI: st("michigan", "Michigan"),
  MN: st("minnesota", "Minnesota"),
  MS: st("mississippi", "Mississippi"),
  MO: st("missouri", "Missouri"),
  MT: st("montana", "Montana"),
  NE: st("nebraska", "Nebraska"),
  NV: st("nevada", "Nevada"),
  NH: st("new-hampshire", "New Hampshire"),
  NJ: st("new-jersey", "New Jersey"),
  NM: st("new-mexico", "New Mexico"),
  NY: st("new-york", "New York"),
  NC: st("north-carolina", "North Carolina"),
  ND: st("north-dakota", "North Dakota"),
  OH: st("ohio", "Ohio"),
  OK: st("oklahoma", "Oklahoma"),
  OR: st("oregon", "Oregon"),
  PA: st("pennsylvania", "Pennsylvania"),
  RI: st("rhode-island", "Rhode Island"),
  SC: st("south-carolina", "South Carolina"),
  SD: st("south-dakota", "South Dakota"),
  TN: st("tennessee", "Tennessee"),
  TX: st("texas", "Texas"),
  UT: st("utah", "Utah"),
  VT: st("vermont", "Vermont"),
  VA: st("virginia", "Virginia"),
  WA: st("washington", "Washington"),
  WV: st("west-virginia", "West Virginia"),
  WI: st("wisconsin", "Wisconsin"),
  WY: st("wyoming", "Wyoming"),
};
