/** US state labels for the funeral directory. */
module.exports = {
  AL: { slug: "alabama", nameEs: "Alabama", nameEn: "Alabama" },
  AK: { slug: "alaska", nameEs: "Alaska", nameEn: "Alaska" },
  AZ: { slug: "arizona", nameEs: "Arizona", nameEn: "Arizona" },
  AR: { slug: "arkansas", nameEs: "Arkansas", nameEn: "Arkansas" },
  CA: { slug: "california", nameEs: "California", nameEn: "California" },
  CO: { slug: "colorado", nameEs: "Colorado", nameEn: "Colorado" },
  CT: { slug: "connecticut", nameEs: "Connecticut", nameEn: "Connecticut" },
  DE: { slug: "delaware", nameEs: "Delaware", nameEn: "Delaware" },
  DC: { slug: "district-of-columbia", nameEs: "Distrito de Columbia", nameEn: "District of Columbia" },
  FL: { slug: "florida", nameEs: "Florida", nameEn: "Florida" },
  GA: { slug: "georgia", nameEs: "Georgia", nameEn: "Georgia" },
  HI: { slug: "hawaii", nameEs: "Hawái", nameEn: "Hawaii" },
  ID: { slug: "idaho", nameEs: "Idaho", nameEn: "Idaho" },
  IL: { slug: "illinois", nameEs: "Illinois", nameEn: "Illinois" },
  IN: { slug: "indiana", nameEs: "Indiana", nameEn: "Indiana" },
  IA: { slug: "iowa", nameEs: "Iowa", nameEn: "Iowa" },
  KS: { slug: "kansas", nameEs: "Kansas", nameEn: "Kansas" },
  KY: { slug: "kentucky", nameEs: "Kentucky", nameEn: "Kentucky" },
  LA: { slug: "louisiana", nameEs: "Luisiana", nameEn: "Louisiana" },
  ME: { slug: "maine", nameEs: "Maine", nameEn: "Maine" },
  MD: { slug: "maryland", nameEs: "Maryland", nameEn: "Maryland" },
  MA: { slug: "massachusetts", nameEs: "Massachusetts", nameEn: "Massachusetts" },
  MI: { slug: "michigan", nameEs: "Míchigan", nameEn: "Michigan" },
  MN: { slug: "minnesota", nameEs: "Minnesota", nameEn: "Minnesota" },
  MS: { slug: "mississippi", nameEs: "Misisipi", nameEn: "Mississippi" },
  MO: { slug: "missouri", nameEs: "Misuri", nameEn: "Missouri" },
  MT: { slug: "montana", nameEs: "Montana", nameEn: "Montana" },
  NE: { slug: "nebraska", nameEs: "Nebraska", nameEn: "Nebraska" },
  NV: { slug: "nevada", nameEs: "Nevada", nameEn: "Nevada" },
  NH: { slug: "new-hampshire", nameEs: "Nuevo Hampshire", nameEn: "New Hampshire" },
  NJ: { slug: "new-jersey", nameEs: "Nueva Jersey", nameEn: "New Jersey" },
  NM: { slug: "new-mexico", nameEs: "Nuevo México", nameEn: "New Mexico" },
  NY: { slug: "new-york", nameEs: "Nueva York", nameEn: "New York" },
  NC: { slug: "north-carolina", nameEs: "Carolina del Norte", nameEn: "North Carolina" },
  ND: { slug: "north-dakota", nameEs: "Dakota del Norte", nameEn: "North Dakota" },
  OH: { slug: "ohio", nameEs: "Ohio", nameEn: "Ohio" },
  OK: { slug: "oklahoma", nameEs: "Oklahoma", nameEn: "Oklahoma" },
  OR: { slug: "oregon", nameEs: "Oregón", nameEn: "Oregon" },
  PA: { slug: "pennsylvania", nameEs: "Pensilvania", nameEn: "Pennsylvania" },
  RI: { slug: "rhode-island", nameEs: "Rhode Island", nameEn: "Rhode Island" },
  SC: { slug: "south-carolina", nameEs: "Carolina del Sur", nameEn: "South Carolina" },
  SD: { slug: "south-dakota", nameEs: "Dakota del Sur", nameEn: "South Dakota" },
  TN: { slug: "tennessee", nameEs: "Tennessee", nameEn: "Tennessee" },
  TX: { slug: "texas", nameEs: "Texas", nameEn: "Texas" },
  UT: { slug: "utah", nameEs: "Utah", nameEn: "Utah" },
  VT: { slug: "vermont", nameEs: "Vermont", nameEn: "Vermont" },
  VA: { slug: "virginia", nameEs: "Virginia", nameEn: "Virginia" },
  WA: { slug: "washington", nameEs: "Washington", nameEn: "Washington" },
  WV: { slug: "west-virginia", nameEs: "Virginia Occidental", nameEn: "West Virginia" },
  WI: { slug: "wisconsin", nameEs: "Wisconsin", nameEn: "Wisconsin" },
  WY: { slug: "wyoming", nameEs: "Wyoming", nameEn: "Wyoming" },
};
