"use strict";

const { pack, ctaEs, ctaEn, SRC } = require("./shared");

module.exports = [
  pack(
    "diferencia-seguro-vida-y-gastos-finales",
    "life-insurance-vs-final-expense",
    ["que-son-polizas-gastos-finales", "seguro-vida-entero-gastos-finales", "cuanta-cobertura-gastos-finales-necesito"],
    {
      question: "¿Cuál es la diferencia entre seguro de vida y seguro de gastos finales?",
      headline: "Seguro de vida y seguro de gastos finales: qué cambia de verdad",
      dek: "El seguro de gastos finales es un tipo de seguro de vida, no un producto aparte. La diferencia está en el tamaño, el propósito y cómo se suele solicitar.",
      pageTitle: "Diferencia entre seguro de vida y gastos finales",
      metaDescription:
        "Qué diferencia hay entre un seguro de vida temporal, un seguro de vida entero y un seguro de gastos finales. Guía clara de Mejor Vida Seguros.",
      keyTakeaways: [
        "Un seguro de gastos finales es un seguro de vida permanente de monto más pequeño, pensado para funeral, cremación y deudas cercanas a la muerte.",
        "Un seguro temporal cubre un plazo (por ejemplo 10 o 20 años) y luego suele terminar si no se convierte o se renueva.",
        "La vida entera tradicional puede ser mucho más grande y servir para reemplazar ingresos o dejar un legado; los gastos finales suelen quedarse en el tamaño de un funeral.",
        "El precio, la edad máxima y las preguntas de salud cambian según el producto. No hay un único “mejor” tipo para todas las familias.",
      ],
      cta: ctaEs,
      blocks: [
        { type: "p", text: "Cuando alguien dice “necesito un seguro de vida”, puede estar pensando en tres cosas distintas. Una es reemplazar el sueldo si muere joven. Otra es dejar un monto grande a un cónyuge o a los hijos. La tercera es más concreta: que la familia no tenga que pedir prestado para el funeral. El seguro de gastos finales responde sobre todo a esa tercera pregunta." },
        { type: "h2", text: "Qué es, en palabras simples, un seguro de vida" },
        { type: "p", text: "Un seguro de vida es un contrato. Usted paga una prima —el precio periódico del seguro— y la compañía promete pagar un beneficio en efectivo a las personas que usted nombra como beneficiarios si usted fallece mientras la póliza está vigente. El beneficiario no está obligado a entregar el cheque a una funeraria. Puede usarlo para el servicio, facturas, viaje de familiares o lo que la familia necesite." },
        { type: "h2", text: "Tres diseños que la gente mezcla" },
        { type: "p", text: "El seguro temporal cubre un número de años. Si usted vive más que ese plazo y no convierte la póliza, la cobertura termina. Suele ser el camino cuando el objetivo es un monto grande a un precio más bajo mientras hay hipoteca o hijos en casa." },
        { type: "p", text: "El seguro de vida entero es permanente: no “vence” a los 70 u 80 como un temporal. La prima, si el contrato es de prima nivelada, se mantiene igual mientras usted pague a tiempo. Prima nivelada significa que el precio mensual no sube solo porque usted cumpla años dentro de esa misma póliza." },
        { type: "p", text: "El seguro de gastos finales suele ser un seguro de vida entero de monto pequeño. No es un producto mágico distinto. Es el mismo tipo de contrato, recortado al tamaño de un funeral, una cremación y algunas deudas. En las compañías que Mejor Vida Seguros cotiza, esos montos suelen moverse entre unos $2,000 y unos $50,000, según producto y edad — no el tamaño de una hipoteca grande." },
        {
          type: "table",
          caption: "Cómo se sienten distintos en la vida real",
          lead: "Esta tabla no dice qué debe comprar. Sirve para ver el propósito, no para elegir una compañía.",
          headers: ["Pregunta", "Temporal", "Vida entera más grande", "Gastos finales"],
          rows: [
            ["¿Para qué se usa más?", "Ingresos o deudas grandes por un plazo", "Protección permanente más amplia", "Funeral, cremación y deudas pequeñas"],
            ["¿Cuánto suele ser el monto?", "A menudo $100,000 o más", "A menudo $50,000 o más", "Suele ser de unos miles hasta cerca de $50,000"],
            ["¿Cuándo termina?", "Al acabar el plazo, si no se convierte", "No vence por edad si sigue pagando", "No vence por edad si sigue pagando"],
            ["¿Hay examen médico?", "A veces sí, a veces un cuestionario", "Depende del monto y la compañía", "En muchos planes de gastos finales no hay examen en consultorio; sí hay preguntas de salud"],
          ],
          foot: "Los rangos son típicos de productos que Mejor Vida Seguros puede cotizar. El número exacto lo fija cada compañía, estado y solicitud.",
        },
        { type: "h2", text: "Qué conviene tener claro antes de elegir" },
        { type: "ul", items: [
          "Si el objetivo es solo el funeral, un monto de gastos finales suele alinearse mejor que un temporal de $250,000.",
          "Si todavía hay hipoteca o personas que viven de su sueldo, un temporal o una vida entera más grande puede ser la conversación principal.",
          "Algunas familias combinan: un temporal mientras trabajan y un gasto final más adelante. Eso no es obligatorio.",
          "Un plan de gastos finales que califica a beneficio completo desde el primer pago no es lo mismo que un plan con periodo de espera. El periodo de espera es el tiempo al inicio en el que una muerte no accidental puede pagar menos que el monto completo.",
        ] },
        { type: "h2", text: "Compañías y productos, después de entender la idea" },
        { type: "p", text: "Mutual of Omaha Living Promise Nivelado, por ejemplo, emite en general de 45 a 85 años, hasta unos $50,000. American Amicable ofrece Golden Solution y Senior Choice, en general de 50 a 85. Accendo Level puede emitir hasta 89, con un tope de $25,000 a los 76–89. Transamerica Immediate Solution llega hasta 85. Esas cifras describen productos distintos; no significan que una compañía “gane” a la otra." },
        {
          type: "faq",
          items: [
            { q: "¿El seguro de gastos finales es un seguro de entierro aparte?", a: "No. “Seguro de entierro” o “seguro funeral” son nombres comunes para un seguro de vida pequeño y permanente. El cheque llega al beneficiario, no automáticamente a la funeraria." },
            { q: "¿Puedo tener temporal y gastos finales a la vez?", a: "Sí, si cada compañía lo permite y el presupuesto da. Son contratos distintos. Un agente debe revisar que no esté pagando dos veces por el mismo objetivo." },
            { q: "¿Cuál es más barato?", a: "Un temporal de monto grande puede costar menos por dólar de cobertura a edades más jóvenes. Un gasto final de $10,000 tiene otro propósito. Comparar solo el precio mensual sin mirar el monto y el plazo lleva a conclusiones equivocadas." },
            { q: "¿Medicare es un tipo de seguro de vida?", a: "No. Medicare es seguro de salud para quienes califican. No está diseñado para pagar funerales." },
          ],
        },
        { type: "sources", items: [SRC.naic, SRC.medicare] },
      ],
    },
    {
      question: "What is the difference between life insurance and final expense insurance?",
      headline: "Life insurance and final expense insurance: what actually changes",
      dek: "Final expense insurance is a kind of life insurance, not a separate invention. The difference is size, purpose, and how people usually apply.",
      pageTitle: "Life insurance vs final expense insurance",
      metaDescription:
        "How term life, larger whole life, and final expense insurance differ in purpose, amount, and how you apply. A plain-language guide from Mejor Vida Insurance.",
      keyTakeaways: [
        "Final expense insurance is smaller permanent life insurance meant for a funeral, cremation, and nearby debts.",
        "Term life covers a set number of years and then usually ends unless you convert or renew.",
        "Larger whole life can replace income or leave a bigger gift; final expense usually stays funeral-sized.",
        "Price, maximum issue age, and health questions vary by product. There is no single best type for every family.",
      ],
      cta: ctaEn,
      blocks: [
        { type: "p", text: "When someone says “I need life insurance,” they may mean three different jobs. One is replacing a paycheck if they die young. Another is leaving a large amount to a spouse or children. The third is narrower: making sure the family does not have to borrow for the funeral. Final expense insurance is built mainly for that third job." },
        { type: "h2", text: "What life insurance means in everyday language" },
        { type: "p", text: "Life insurance is a contract. You pay a premium — the regular price of the policy — and the company promises a cash benefit to the people you name as beneficiaries if you die while the policy is in force. The beneficiary is not required to hand the check to a funeral home. They can use it for the service, bills, travel, or whatever the family needs." },
        { type: "h2", text: "Three designs people often mix together" },
        { type: "p", text: "Term life covers a number of years. If you outlive that term and do not convert the policy, coverage ends. It is often the path when the goal is a large amount at a lower price while there is a mortgage or children at home." },
        { type: "p", text: "Whole life is permanent: it does not “expire at 70 or 80” the way a term policy can. If the contract has a level premium, the price stays the same while you pay on time. Level premium means the monthly price does not rise just because you have a birthday inside that same policy." },
        { type: "p", text: "Final expense insurance is usually small whole life. It is not a magic third product. It is the same kind of contract, sized for a funeral, a cremation, and some debts. On products Mejor Vida Insurance can quote, those amounts often run from about $2,000 to about $50,000, depending on the product and age — not the size of a large mortgage." },
        {
          type: "table",
          caption: "How they feel different in real life",
          lead: "This table is about purpose. It is not a shopping ranking of companies.",
          headers: ["Question", "Term", "Larger whole life", "Final expense"],
          rows: [
            ["Most common job", "Income or large debts for a period", "Broader permanent protection", "Funeral, cremation, and small debts"],
            ["Typical amount", "Often $100,000 or more", "Often $50,000 or more", "Usually a few thousand up to about $50,000"],
            ["When it ends", "When the term ends, if not converted", "Does not age out if you keep paying", "Does not age out if you keep paying"],
            ["Medical exam?", "Sometimes yes, sometimes a questionnaire", "Depends on amount and company", "Many final expense plans skip an in-office exam; health questions still apply"],
          ],
          foot: "Ranges describe products Mejor Vida Insurance can quote. The exact number is set by company, state, and application.",
        },
        { type: "h2", text: "What to settle before you pick a type" },
        { type: "ul", items: [
          "If the only goal is the funeral, a final expense amount usually lines up better than a $250,000 term policy.",
          "If there is still a mortgage or people living on your paycheck, term or larger whole life may be the main conversation.",
          "Some families combine: term while working, final expense later. That is optional, not required.",
          "A final expense plan that can pay the full amount from the first payment is not the same as a waiting-period plan. A waiting period is the early time when a non-accidental death may pay less than the full amount.",
        ] },
        { type: "h2", text: "Companies and products, after the idea is clear" },
        { type: "p", text: "Mutual of Omaha Living Promise Level, for example, typically issues ages 45–85, up to about $50,000. American Amicable offers Golden Solution and Senior Choice, typically ages 50–85. Accendo Level can issue through 89, with a $25,000 cap at ages 76–89. Transamerica Immediate Solution goes through 85. Those figures describe different products; they do not mean one company “wins.”" },
        {
          type: "faq",
          items: [
            { q: "Is final expense a separate “burial policy”?", a: "No. “Burial insurance” and “funeral insurance” are common names for small permanent life insurance. The check goes to the beneficiary, not automatically to the funeral home." },
            { q: "Can I have term and final expense at the same time?", a: "Yes, if each company allows it and the budget supports it. They are separate contracts. An agent should check that you are not paying twice for the same goal." },
            { q: "Which one is cheaper?", a: "A large term policy can cost less per dollar of coverage at younger ages. A $10,000 final expense plan has a different job. Comparing only the monthly price without looking at amount and duration leads to the wrong conclusion." },
            { q: "Is Medicare a type of life insurance?", a: "No. Medicare is health insurance for people who qualify. It is not designed to pay for funerals." },
          ],
        },
        { type: "sources", items: [SRC.naic, SRC.medicare] },
      ],
    }
  ),

  pack(
    "que-pasa-sin-seguro-gastos-finales",
    "what-happens-without-final-expense-insurance",
    ["que-son-gastos-finales", "cuanto-cuesta-un-funeral", "como-pagar-un-funeral"],
    {
      question: "¿Qué pasa si no tengo seguro de gastos finales?",
      headline: "Si no hay seguro de gastos finales, ¿quién paga?",
      dek: "Sin un plan, la cuenta del funeral no desaparece. Suele caer en la familia, en ahorros o en deudas nuevas. El pago de $255 del Seguro Social no alcanza para un servicio típico.",
      pageTitle: "Qué pasa si no tengo seguro de gastos finales",
      metaDescription:
        "Qué enfrenta la familia si no hay seguro de gastos finales: facturas del funeral, el pago de $255 del Seguro Social y otras vías de pago. Guía de Mejor Vida Seguros.",
      keyTakeaways: [
        "Alguien tiene que pagar el funeral, la cremación o el traslado. Si no hay dinero apartado, suele ser la familia.",
        "El Seguro Social puede pagar un único pago de $255 a un cónyuge sobreviviente que califique, o a un hijo que califique si no hay cónyuge. Hay que solicitarlo, en general dentro de dos años.",
        "Medicare no está pensado para pagar funerales.",
        "No tener seguro no es ilegal. Significa que hay que usar ahorros, un contrato prepagado, ayuda de familiares o, en algunos casos, un servicio más sencillo de lo que la familia quería.",
      ],
      cta: ctaEs,
      blocks: [
        { type: "p", text: "La pregunta no es abstracta. Cuando alguien fallece, la funeraria pide decisiones en pocos días: cremación o entierro, velatorio o no, traslado, urna o ataúd. Cada decisión tiene un precio. Si no hay un fondo listo, la familia improvisa." },
        { type: "h2", text: "Quién queda a cargo de la cuenta" },
        { type: "p", text: "La funeraria cobra a la persona que firma el contrato de servicios. Muchas veces es un hijo, un cónyuge o un hermano. Si esa persona no puede pagar de contado, puede usar tarjeta, un préstamo o pedir dinero a otros parientes. Eso no es un “castigo” de una ley de seguros. Es simplemente quién firmó." },
        { type: "p", text: "Un seguro de gastos finales no borra el dolor. Cambia el momento del dinero: el beneficiario recibe un cheque de la aseguradora y puede usarlo para esa cuenta u otras deudas. Sin ese cheque, el mismo trabajo sigue existiendo." },
        { type: "h2", text: "Lo que sí existe sin un seguro privado" },
        { type: "p", text: "La Administración del Seguro Social describe un pago único por fallecimiento de $255. Lo puede recibir un cónyuge que califique. Si no hay cónyuge, algunos hijos pueden calificar. Hay que solicitarlo, en general dentro de dos años del fallecimiento. No se envía automáticamente a la funeraria." },
        { type: "note", text: "Ese $255 no se actualiza con el costo de un funeral. Un proyecto de ley ha propuesto subirlo; no es ley vigente. En esta guía usamos la cifra oficial actual de $255." },
        { type: "p", text: "Medicare cubre servicios de salud que califican, no el funeral. Si alguien espera que “el gobierno pague el entierro,” esa espera no coincide con lo que Medicare publica para el público." },
        { type: "p", text: "Algunos veteranos pueden tener ayudas de entierro del Departamento de Asuntos de Veteranos. Esas reglas son propias del VA y dependen del servicio y de la situación. No sustituyen, por sí solas, un funeral promedio." },
        {
          type: "table",
          caption: "Dinero que a veces aparece — y lo que no cubre",
          lead: "Use esta tabla para no confundir un pago pequeño del gobierno con el costo de un servicio.",
          headers: ["Fuente", "Qué es", "Límite importante"],
          rows: [
            ["Pago único del Seguro Social", "$255 si hay un sobreviviente que califique", "Hay que pedir el pago; no cubre un funeral típico"],
            ["Medicare", "Seguro de salud", "No está diseñado para funerales"],
            ["Ahorros o cuenta conjunta", "Lo que la familia ya tiene", "Puede no estar líquido a tiempo"],
            ["Contrato prepagado con la funeraria", "Servicios pagados por adelantado según el contrato", "Suele atarse a una funeraria y a un paquete concreto"],
            ["Seguro de gastos finales", "Cheque al beneficiario", "Solo si la póliza está vigente y el fallecimiento está cubierto"],
          ],
          foot: "Ninguna fila garantiza aprobación ni un monto. Cada programa y cada contrato tiene sus propias reglas.",
        },
        { type: "h2", text: "Qué suele ocurrir en la práctica" },
        { type: "ul", items: [
          "La familia elige un servicio más simple de lo que la persona habría querido, para bajar la factura.",
          "Varios parientes se dividen el costo y luego discuten quién puso más.",
          "Se usa una tarjeta de crédito y la deuda queda meses después del funeral.",
          "Si hay un prepago, hay que confirmar qué está incluido: parcela, lápida y flores suelen ir aparte.",
        ] },
        { type: "h2", text: "Un seguro no es la única respuesta — pero es una respuesta" },
        { type: "p", text: "Algunas familias prefieren ahorrar en una cuenta aparte o firmar un prepago. Eso puede funcionar si el dinero realmente está ahí cuando se necesita y si el contrato dice con claridad qué pasa si se mudan. Un seguro de gastos finales mueve el pago a un beneficiario en efectivo. Mejor Vida Seguros compara compañías para esa vía; no le dice que ignore ahorros o un prepago si ya los tiene." },
        {
          type: "faq",
          items: [
            { q: "¿La funeraria puede negarse a recoger el cuerpo si no hay seguro?", a: "Las reglas de cada estado y cada funeraria varían. En la práctica, alguien debe autorizar y pagar servicios. No inventamos una regla nacional de “no recogen sin póliza.” Pregunte a la funeraria local y, si hace falta, al regulador estatal de funerarias." },
            { q: "¿El $255 se deposita solo?", a: "No. La SSA indica que hay que solicitar el pago, en general dentro de dos años." },
            { q: "¿Si no compro seguro, mis hijos heredan la deuda del funeral automáticamente?", a: "El que firma el contrato de la funeraria suele ser quien debe esa factura. Las deudas de una herencia siguen las reglas del estado y del caudal hereditario. Eso es tema de un abogado, no de una cotización de seguro." },
          ],
        },
        { type: "sources", items: [SRC.ssa, SRC.medicare, SRC.nfda, SRC.ftc] },
      ],
    },
    {
      question: "What happens if I do not have final expense insurance?",
      headline: "If there is no final expense insurance, who pays?",
      dek: "Without a plan, the funeral bill does not vanish. It usually lands on family, savings, or new debt. Social Security’s $255 payment does not cover a typical service.",
      pageTitle: "What happens without final expense insurance",
      metaDescription:
        "What families face without final expense insurance: funeral bills, Social Security’s $255 payment, and other ways to pay. A guide from Mejor Vida Insurance.",
      keyTakeaways: [
        "Someone has to pay for the funeral, cremation, or transfer. If no money is set aside, it is often the family.",
        "Social Security may pay a one-time $255 amount to an eligible surviving spouse, or to an eligible child if there is no spouse. You generally must apply within two years.",
        "Medicare is not designed to pay for funerals.",
        "Going without insurance is not illegal. It means using savings, a prepaid contract, help from relatives, or sometimes a simpler service than the family wanted.",
      ],
      cta: ctaEn,
      blocks: [
        { type: "p", text: "This is not an abstract question. When someone dies, the funeral home asks for decisions in a few days: cremation or burial, viewing or not, transfer, urn or casket. Each choice has a price. If there is no fund ready, the family improvises." },
        { type: "h2", text: "Who is on the hook for the bill" },
        { type: "p", text: "The funeral home bills the person who signs the services contract. That is often a child, a spouse, or a sibling. If that person cannot pay in cash, they may use a card, a loan, or ask other relatives. That is not an insurance-law “penalty.” It is simply who signed." },
        { type: "p", text: "Final expense insurance does not erase grief. It changes the timing of money: the beneficiary receives a check from the insurer and can use it for that bill or other debts. Without that check, the same work still exists." },
        { type: "h2", text: "What still exists without a private policy" },
        { type: "p", text: "The Social Security Administration describes a one-time lump-sum death payment of $255. An eligible spouse may receive it. If there is no spouse, some children may qualify. You generally must apply within two years of the death. It is not sent automatically to the funeral home." },
        { type: "note", text: "That $255 is not indexed to funeral prices. A bill has been proposed to raise it; it is not current law. This guide uses the official $255 figure." },
        { type: "p", text: "Medicare covers qualifying health services, not funerals. If someone is waiting for “the government to pay for the burial,” that wait does not match what Medicare publishes for the public." },
        { type: "p", text: "Some veterans may have burial help from the Department of Veterans Affairs. Those rules belong to the VA and depend on service and situation. They do not, by themselves, replace an average funeral." },
        {
          type: "table",
          caption: "Money that sometimes appears — and what it does not cover",
          lead: "Use this table so a small government payment is not mistaken for the cost of a service.",
          headers: ["Source", "What it is", "Important limit"],
          rows: [
            ["Social Security lump-sum", "$255 if an eligible survivor qualifies", "You must apply; it does not cover a typical funeral"],
            ["Medicare", "Health insurance", "Not designed for funerals"],
            ["Savings or a joint account", "What the family already has", "May not be liquid in time"],
            ["Prepaid funeral-home contract", "Services paid in advance as the contract writes them", "Usually tied to one funeral home and a specific package"],
            ["Final expense insurance", "A check to the beneficiary", "Only if the policy is in force and the death is covered"],
          ],
          foot: "No row guarantees approval or an amount. Each program and contract has its own rules.",
        },
        { type: "h2", text: "What often happens in practice" },
        { type: "ul", items: [
          "The family chooses a simpler service than the person would have wanted, to lower the bill.",
          "Several relatives split the cost and later argue about who paid more.",
          "A credit card is used, and the debt remains months after the funeral.",
          "If there is a prepay, someone still has to confirm what is included: plot, marker, and flowers are often extra.",
        ] },
        { type: "h2", text: "Insurance is not the only answer — but it is one answer" },
        { type: "p", text: "Some families prefer a dedicated savings account or a prepaid contract. That can work if the money is actually there when it is needed and if the contract is clear about a move. Final expense insurance sends cash to a beneficiary. Mejor Vida Insurance compares companies for that path; it does not tell you to ignore savings or a prepay you already have." },
        {
          type: "faq",
          items: [
            { q: "Can a funeral home refuse to pick up the body if there is no insurance?", a: "State and funeral-home rules vary. In practice, someone must authorize and pay for services. We do not invent a national “no pickup without a policy” rule. Ask the local funeral home and, if needed, the state funeral regulator." },
            { q: "Is the $255 deposited automatically?", a: "No. SSA says you must apply, generally within two years." },
            { q: "If I skip insurance, do my children automatically inherit the funeral debt?", a: "The person who signs the funeral-home contract is usually responsible for that bill. Estate debts follow state law and the estate itself. That is a question for an attorney, not an insurance quote." },
          ],
        },
        { type: "sources", items: [SRC.ssa, SRC.medicare, SRC.nfda, SRC.ftc] },
      ],
    }
  ),
];
