/**
 * South Carolina city guides. Estimator column is South Carolina Funeralocity averages
 * (captured 26 Jul 2026). No local home publishes a first-party four-package list here,
 * so the chart is estimator-only.
 */
const { makeCity } = require("./sc-factory");

const HERO = {
  heroVer: "landmark-v1",
};

const CITIES = [
  {
    "slug": "charleston",
    "name": "Charleston"
  },
  {
    "slug": "columbia",
    "name": "Columbia"
  },
  {
    "slug": "north-charleston",
    "name": "North Charleston"
  },
  {
    "slug": "mount-pleasant",
    "name": "Mount Pleasant"
  },
  {
    "slug": "rock-hill",
    "name": "Rock Hill"
  },
  {
    "slug": "greenville",
    "name": "Greenville"
  }
];

function near(except) {
  return CITIES.filter((c) => c.slug !== except);
}

const shared = {
  analysisSameEs:
    "Un paquete con el mismo nombre puede incluir o no el ataúd, la urna o el velatorio. Lea la lista de esa funeraria. El lote del cementerio no va en ninguno.",
  analysisSameEn:
    "A package with the same name may or may not include the casket, urn, or visitation. Read that funeral home’s list. The cemetery plot is in none of them.",
  prepaidCemEs: "o en el cementerio que elija",
  prepaidCemEn: "or at the cemetery you choose",
  tableFootEs:
    "La columna del estimador son promedios de Carolina del Sur de Funeralocity (26 jul. 2026). Esos promedios son de paquetes de funeraria. No incluyen el lote, abrir y cerrar la tumba, la bóveda ni la lápida.",
  tableFootEn:
    "The estimator column is South Carolina Funeralocity averages (26 Jul 2026). Those averages are funeral-home packages. They do not include the plot, opening and closing, the vault, or the marker.",
  resaleHref: "https://www.gravesolutions.com/for-sale/cemetery-properties/south-carolina",
};

module.exports = [
  makeCity({
    ...shared,
    ...HERO,
    slug: "charleston",
    heroFile: "charleston-rainbow-row",
    heroClass: "sc-hero--charleston",
    heroW: 1200,
    heroH: 900,
    nameEn: "Charleston",
    heroCaptionEs: "Rainbow Row, Charleston",
    heroCaptionEn: "Rainbow Row, Charleston",
    countyEs: "condado de Charleston",
    countyEn: "Charleston County",
    metroEs: ["Charleston","James Island","West Ashley","Daniel Island"],
    metroEn: ["Charleston","James Island","West Ashley","Daniel Island"],
    metroTitleEs: "Charleston y el condado de Charleston",
    metroTitleEn: "Charleston and Charleston County",
    nearbyGuides: near("charleston"),
    faqPlotEs: "No. El precio de la funeraria no compra el espacio en el cementerio. Esta guía no publica un precio de lote nuevo para Charleston. Pida la lista en el cementerio que elija. Abrir y cerrar, la bóveda y la lápida son cargos aparte.",
    faqPlotEn: "No. The funeral-home price does not buy the cemetery space. This guide does not publish a new-lot price for Charleston. Ask the cemetery you choose for its list. Opening and closing, the vault, and the marker are separate charges.",
    officesNoteEs: "Estas cifras serían del cementerio, no de la funeraria. No hay un precio de lote nuevo publicado para Charleston en esta página.",
    officesNoteEn: "These figures would come from the cemetery, not the funeral home. This page does not have a published new-lot price for Charleston.",
    newListEs: "No hay un precio de lote nuevo publicado para Charleston en esta guía. Llame al cementerio que elija y pida la lista por escrito. Los anuncios de particulares están en el tablero de Carolina del Sur de Grave Solutions.",
    newListEn: "This guide does not have a published new-lot price for Charleston. Call the cemetery you choose and ask for the list in writing. Private-party ads are on the South Carolina Grave Solutions board.",
    officesEs: ["Charleston. Lote nuevo: pida la lista en el cementerio que elija."],
    officesEn: ["Charleston. New lot: ask the cemetery you choose for the list."],
    analysisPlotEs: "El lote no está en el promedio de la funeraria. En Charleston no hay un precio de lote nuevo publicado en esta guía. Los anuncios de particulares están en el tablero de Carolina del Sur de Grave Solutions.",
    analysisPlotEn: "The plot is not in the funeral-home average. This guide does not have a published new-lot price for Charleston. Private-party ads are on the South Carolina Grave Solutions board.",
    plotNew: null,
    plotResale: null,
  }),
  makeCity({
    ...shared,
    ...HERO,
    slug: "columbia",
    heroFile: "columbia-state-house",
    heroClass: "sc-hero--columbia",
    heroW: 1144,
    heroH: 900,
    nameEn: "Columbia",
    heroCaptionEs: "Capitolio de Carolina del Sur, Columbia",
    heroCaptionEn: "South Carolina State House, Columbia",
    countyEs: "condado de Richland",
    countyEn: "Richland County",
    metroEs: ["Columbia","Forest Acres","Cayce","West Columbia"],
    metroEn: ["Columbia","Forest Acres","Cayce","West Columbia"],
    metroTitleEs: "Columbia y el condado de Richland",
    metroTitleEn: "Columbia and Richland County",
    nearbyGuides: near("columbia"),
    faqPlotEs: "No. El precio de la funeraria no compra el espacio. El 28 de septiembre de 2026, anuncios de particulares para Greenlawn Memorial Park, en Columbia, pedían $2,250 por cada uno de dos espacios, y $9,840 por dos lotes que incluyen bóvedas. Eso es lo que pide el vendedor, no la lista del cementerio.",
    faqPlotEn: "No. The funeral-home price does not buy the space. On September 28, 2026, private ads for Greenlawn Memorial Park in Columbia asked $2,250 for each of two spaces, and $9,840 for two lots that include vaults. Those are asking prices, not the cemetery’s price list.",
    officesNoteEs: "Esas cifras son anuncios de particulares. El de $9,840 incluye bóvedas. No es un precio de lote nuevo del cementerio.",
    officesNoteEn: "Those figures are private ads. The $9,840 ad includes vaults. They are not a new-lot price from the cemetery.",
    newListEs: "El 28 de septiembre de 2026, Grave Solutions mostraba en Greenlawn Memorial Park, Columbia, dos espacios a $2,250 cada uno y dos lotes con bóvedas a $9,840. Pida a la oficina la lista de lotes nuevos.",
    newListEn: "On September 28, 2026, Grave Solutions showed two spaces at $2,250 each and two lots with vaults at $9,840 at Greenlawn Memorial Park, Columbia. Ask the office for the new-lot list.",
    officesEs: ["Greenlawn Memorial Park, Columbia. Reventa vista el 28 de septiembre de 2026: $2,250 cada espacio, o $9,840 por dos lotes con bóvedas. Lote nuevo: pida la lista."],
    officesEn: ["Greenlawn Memorial Park, Columbia. Resale seen September 28, 2026: $2,250 each space, or $9,840 for two lots with vaults. New lot: ask for the list."],
    analysisPlotEs: "El 28 de septiembre de 2026, anuncios en Greenlawn Memorial Park pedían <strong>$2,250</strong> por espacio y <strong>$9,840</strong> por dos lotes con bóvedas. Eso no está en el promedio de la funeraria.",
    analysisPlotEn: "On September 28, 2026, ads at Greenlawn Memorial Park asked <strong>$2,250</strong> per space and <strong>$9,840</strong> for two lots with vaults. That is not in the funeral-home average.",
    plotNew: null,
    plotResale: null,
  }),
  makeCity({
    ...shared,
    ...HERO,
    slug: "north-charleston",
    heroFile: "north-charleston-coliseum",
    heroClass: "sc-hero--north-charleston",
    heroW: 1200,
    heroH: 900,
    nameEn: "North Charleston",
    heroCaptionEs: "Coliseo de North Charleston",
    heroCaptionEn: "North Charleston Coliseum",
    countyEs: "condado de Charleston",
    countyEn: "Charleston County",
    metroEs: ["North Charleston","Ladson","Hanahan","Goose Creek"],
    metroEn: ["North Charleston","Ladson","Hanahan","Goose Creek"],
    metroTitleEs: "North Charleston y el condado de Charleston",
    metroTitleEn: "North Charleston and Charleston County",
    nearbyGuides: near("north-charleston"),
    faqPlotEs: "No. El precio de la funeraria no compra el espacio en el cementerio. Esta guía no publica un precio de lote nuevo para North Charleston. Pida la lista en el cementerio que elija. Abrir y cerrar, la bóveda y la lápida son cargos aparte.",
    faqPlotEn: "No. The funeral-home price does not buy the cemetery space. This guide does not publish a new-lot price for North Charleston. Ask the cemetery you choose for its list. Opening and closing, the vault, and the marker are separate charges.",
    officesNoteEs: "Estas cifras serían del cementerio, no de la funeraria. No hay un precio de lote nuevo publicado para North Charleston en esta página.",
    officesNoteEn: "These figures would come from the cemetery, not the funeral home. This page does not have a published new-lot price for North Charleston.",
    newListEs: "No hay un precio de lote nuevo publicado para North Charleston en esta guía. Llame al cementerio que elija y pida la lista por escrito. Los anuncios de particulares están en el tablero de Carolina del Sur de Grave Solutions.",
    newListEn: "This guide does not have a published new-lot price for North Charleston. Call the cemetery you choose and ask for the list in writing. Private-party ads are on the South Carolina Grave Solutions board.",
    officesEs: ["North Charleston. Lote nuevo: pida la lista en el cementerio que elija."],
    officesEn: ["North Charleston. New lot: ask the cemetery you choose for the list."],
    analysisPlotEs: "El lote no está en el promedio de la funeraria. En North Charleston no hay un precio de lote nuevo publicado en esta guía. Los anuncios de particulares están en el tablero de Carolina del Sur de Grave Solutions.",
    analysisPlotEn: "The plot is not in the funeral-home average. This guide does not have a published new-lot price for North Charleston. Private-party ads are on the South Carolina Grave Solutions board.",
    plotNew: null,
    plotResale: null,
  }),
  makeCity({
    ...shared,
    ...HERO,
    slug: "mount-pleasant",
    heroFile: "mount-pleasant-ravenel-bridge",
    heroClass: "sc-hero--mount-pleasant",
    heroW: 1125,
    heroH: 900,
    nameEn: "Mount Pleasant",
    heroCaptionEs: "Puente Arthur Ravenel Jr., Mount Pleasant",
    heroCaptionEn: "Arthur Ravenel Jr. Bridge, Mount Pleasant",
    countyEs: "condado de Charleston",
    countyEn: "Charleston County",
    metroEs: ["Mount Pleasant","Sullivan's Island","Isle of Palms","Awendaw"],
    metroEn: ["Mount Pleasant","Sullivan's Island","Isle of Palms","Awendaw"],
    metroTitleEs: "Mount Pleasant y el condado de Charleston",
    metroTitleEn: "Mount Pleasant and Charleston County",
    nearbyGuides: near("mount-pleasant"),
    faqPlotEs: "No. El precio de la funeraria no compra el espacio en el cementerio. Esta guía no publica un precio de lote nuevo para Mount Pleasant. Pida la lista en el cementerio que elija. Abrir y cerrar, la bóveda y la lápida son cargos aparte.",
    faqPlotEn: "No. The funeral-home price does not buy the cemetery space. This guide does not publish a new-lot price for Mount Pleasant. Ask the cemetery you choose for its list. Opening and closing, the vault, and the marker are separate charges.",
    officesNoteEs: "Estas cifras serían del cementerio, no de la funeraria. No hay un precio de lote nuevo publicado para Mount Pleasant en esta página.",
    officesNoteEn: "These figures would come from the cemetery, not the funeral home. This page does not have a published new-lot price for Mount Pleasant.",
    newListEs: "No hay un precio de lote nuevo publicado para Mount Pleasant en esta guía. Llame al cementerio que elija y pida la lista por escrito. Los anuncios de particulares están en el tablero de Carolina del Sur de Grave Solutions.",
    newListEn: "This guide does not have a published new-lot price for Mount Pleasant. Call the cemetery you choose and ask for the list in writing. Private-party ads are on the South Carolina Grave Solutions board.",
    officesEs: ["Mount Pleasant. Lote nuevo: pida la lista en el cementerio que elija."],
    officesEn: ["Mount Pleasant. New lot: ask the cemetery you choose for the list."],
    analysisPlotEs: "El lote no está en el promedio de la funeraria. En Mount Pleasant no hay un precio de lote nuevo publicado en esta guía. Los anuncios de particulares están en el tablero de Carolina del Sur de Grave Solutions.",
    analysisPlotEn: "The plot is not in the funeral-home average. This guide does not have a published new-lot price for Mount Pleasant. Private-party ads are on the South Carolina Grave Solutions board.",
    plotNew: null,
    plotResale: null,
  }),
  makeCity({
    ...shared,
    ...HERO,
    slug: "rock-hill",
    heroFile: "rock-hill-winthrop",
    heroClass: "sc-hero--rock-hill",
    heroW: 1494,
    heroH: 895,
    nameEn: "Rock Hill",
    heroCaptionEs: "Entrada de Winthrop University, Rock Hill",
    heroCaptionEn: "Winthrop University gateway, Rock Hill",
    countyEs: "condado de York",
    countyEn: "York County",
    metroEs: ["Rock Hill","Fort Mill","Tega Cay","York"],
    metroEn: ["Rock Hill","Fort Mill","Tega Cay","York"],
    metroTitleEs: "Rock Hill y el condado de York",
    metroTitleEn: "Rock Hill and York County",
    nearbyGuides: near("rock-hill"),
    faqPlotEs: "No. El precio de la funeraria no compra el espacio en el cementerio. Esta guía no publica un precio de lote nuevo para Rock Hill. Pida la lista en el cementerio que elija. Abrir y cerrar, la bóveda y la lápida son cargos aparte.",
    faqPlotEn: "No. The funeral-home price does not buy the cemetery space. This guide does not publish a new-lot price for Rock Hill. Ask the cemetery you choose for its list. Opening and closing, the vault, and the marker are separate charges.",
    officesNoteEs: "Estas cifras serían del cementerio, no de la funeraria. No hay un precio de lote nuevo publicado para Rock Hill en esta página.",
    officesNoteEn: "These figures would come from the cemetery, not the funeral home. This page does not have a published new-lot price for Rock Hill.",
    newListEs: "No hay un precio de lote nuevo publicado para Rock Hill en esta guía. Llame al cementerio que elija y pida la lista por escrito. Los anuncios de particulares están en el tablero de Carolina del Sur de Grave Solutions.",
    newListEn: "This guide does not have a published new-lot price for Rock Hill. Call the cemetery you choose and ask for the list in writing. Private-party ads are on the South Carolina Grave Solutions board.",
    officesEs: ["Rock Hill. Lote nuevo: pida la lista en el cementerio que elija."],
    officesEn: ["Rock Hill. New lot: ask the cemetery you choose for the list."],
    analysisPlotEs: "El lote no está en el promedio de la funeraria. En Rock Hill no hay un precio de lote nuevo publicado en esta guía. Los anuncios de particulares están en el tablero de Carolina del Sur de Grave Solutions.",
    analysisPlotEn: "The plot is not in the funeral-home average. This guide does not have a published new-lot price for Rock Hill. Private-party ads are on the South Carolina Grave Solutions board.",
    plotNew: null,
    plotResale: null,
  }),
  makeCity({
    ...shared,
    ...HERO,
    slug: "greenville",
    heroFile: "greenville-falls-park",
    heroClass: "sc-hero--greenville",
    heroW: 1353,
    heroH: 900,
    nameEn: "Greenville",
    heroCaptionEs: "Falls Park en el río Reedy, Greenville",
    heroCaptionEn: "Falls Park on the Reedy, Greenville",
    countyEs: "condado de Greenville",
    countyEn: "Greenville County",
    metroEs: ["Greenville","Mauldin","Simpsonville","Travelers Rest"],
    metroEn: ["Greenville","Mauldin","Simpsonville","Travelers Rest"],
    metroTitleEs: "Greenville y el condado de Greenville",
    metroTitleEn: "Greenville and Greenville County",
    nearbyGuides: near("greenville"),
    faqPlotEs: "No. El precio de la funeraria no compra el espacio. El 28 de septiembre de 2026, un anuncio de particular para una cripta de césped de doble profundidad en Greenlawn Memorial Gardens, Greenville, pedía $12,284 e incluía dos aperturas y cierres. Es un paquete, no un lote sencillo, y no es la lista del cementerio.",
    faqPlotEn: "No. The funeral-home price does not buy the space. On September 28, 2026, a private ad for a double-depth lawn crypt at Greenlawn Memorial Gardens in Greenville asked $12,284 and included two openings and closings. That is a package, not a plain grave space, and it is not the cemetery’s price list.",
    officesNoteEs: "La cifra de $12,284 es un anuncio de una cripta con aperturas incluidas. No es un precio de lote nuevo.",
    officesNoteEn: "The $12,284 figure is an ad for a crypt with openings included. It is not a new-lot price.",
    newListEs: "El 28 de septiembre de 2026, Grave Solutions mostraba una cripta de césped de doble profundidad en Greenlawn Memorial Gardens, Greenville, a $12,284, con dos aperturas y cierres. Pida a la oficina la lista de lotes nuevos.",
    newListEn: "On September 28, 2026, Grave Solutions showed a double-depth lawn crypt at Greenlawn Memorial Gardens, Greenville, at $12,284, with two openings and closings. Ask the office for the new-lot list.",
    officesEs: ["Greenlawn Memorial Gardens, Greenville. Reventa vista el 28 de septiembre de 2026: cripta doble a $12,284 con dos aperturas. Lote nuevo: pida la lista."],
    officesEn: ["Greenlawn Memorial Gardens, Greenville. Resale seen September 28, 2026: double crypt at $12,284 with two openings. New lot: ask for the list."],
    analysisPlotEs: "Un anuncio del 28 de septiembre de 2026 pedía <strong>$12,284</strong> por una cripta de césped de doble profundidad, con dos aperturas incluidas. Eso no está en el promedio de la funeraria.",
    analysisPlotEn: "An ad on September 28, 2026 asked <strong>$12,284</strong> for a double-depth lawn crypt, with two openings included. That is not in the funeral-home average.",
    plotNew: null,
    plotResale: null,
  })
];
